// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace zmdh.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20220601202704_final")]
    partial class final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Agree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HulpverlenerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OuderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("HulpverlenerId");

                    b.HasIndex("OuderId")
                        .IsUnique();

                    b.ToTable("Aanmeldingen");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HulpverlenerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OuderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("HulpverlenerId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OuderId")
                        .IsUnique();

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68714c14-cd9d-447a-92b8-eea67f1bceb9",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFIpkMkCpC+Uv/R84y5KJEx0qQg5DblN/pZhS7sn39FhWuINUWJrrs6hvojAecehkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f91c88c4-736a-4e9a-a4bb-52deeffdb25c",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e574",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb9f7de4-8a7b-4793-a9fa-5969f55949ec",
                            Email = "admin2@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN2@ADMIN.COM",
                            NormalizedUserName = "ADMIN2@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEG1HQbAyKde8Pom+yV5EfLaBY/uxHTvbQU8SmwgxQX8U9mt/dkKwdP0mVppQeBGxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04587595-28dc-4912-bafe-bbffa4677f47",
                            TwoFactorEnabled = false,
                            UserName = "admin2@admin.com"
                        },
                        new
                        {
                            Id = "a99be1c0-aq65-4af8-br17-00bd9674e571",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7153435b-d6a9-47f4-99ca-91bf66f3d087",
                            Email = "mod@mod.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MOD@MOD.COM",
                            NormalizedUserName = "MOD@MOD.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDUcuDFYfXfjjQe13ciaX1A4vVy+gSKFNgbXyzRzR5LL4ssCpoBgdKeIX1xkdzMpLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cc5a137-55a3-47a7-8adc-c24409220bf7",
                            TwoFactorEnabled = false,
                            UserName = "mod@mod.com"
                        },
                        new
                        {
                            Id = "6c26c683-3d56-4b10-a671-9c0565acba97",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd590c96-9dbe-4800-b7d7-5bf8a5a83b28",
                            Email = "kees@gmail.com",
                            EmailConfirmed = false,
                            HulpverlenerId = 1,
                            LockoutEnabled = true,
                            NormalizedEmail = "KEES@GMAIL.COM",
                            NormalizedUserName = "KEES@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEXpvyl2BKzNwW1I9LGM9OkOeqfSurn77d5PIwFsVJVqsysz2CKYDRVci476R9uLgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fedf8ab5-530d-4597-b25c-d47bcd939d02",
                            TwoFactorEnabled = false,
                            UserName = "kees@gmail.com"
                        },
                        new
                        {
                            Id = "4a02ed90-00c0-4a74-b95e-a54722f1c734",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50127f3a-067d-4fae-9a8f-671544770145",
                            Email = "krystel@gmail.com",
                            EmailConfirmed = false,
                            HulpverlenerId = 2,
                            LockoutEnabled = true,
                            NormalizedEmail = "KRYSTEL@GMAIL.COM",
                            NormalizedUserName = "KRYSTEL@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEK2HvsN4orPPDmqu5uSheEMKjQ0WzBtqUiSj4CsrLB4PZLe2hGa2A9TkshVetI9jvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c502ff70-6e4f-4ff7-abae-80e58e450f82",
                            TwoFactorEnabled = false,
                            UserName = "krystel@gmail.com"
                        },
                        new
                        {
                            Id = "8c74234a-facb-40fb-b812-f45b1f328867",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69fc0001-c6e9-41ea-9716-fd9c3d1178e9",
                            Email = "sugodies@gmail.com",
                            EmailConfirmed = false,
                            HulpverlenerId = 3,
                            LockoutEnabled = true,
                            NormalizedEmail = "SUGODIES@GMAIL.COM",
                            NormalizedUserName = "SUGODIES@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOhPaBbQSUk6RX6jOj6nm1ZFSIRSOEMSAfwbNgCOg8+SB9LpoAnjvnq8fnogSKmSrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee208317-2d33-4270-8824-a1aa18699fcc",
                            TwoFactorEnabled = false,
                            UserName = "sugodies@gmail.com"
                        },
                        new
                        {
                            Id = "e0fd4978-7f42-42d9-a3d8-0efbdd40188b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4d5cfc6-6d49-4467-ad06-7f79ce0ce8d3",
                            Email = "melissa@gmail.com",
                            EmailConfirmed = false,
                            HulpverlenerId = 4,
                            LockoutEnabled = true,
                            NormalizedEmail = "MELISSA@GMAIL.COM",
                            NormalizedUserName = "MELISSA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPrZn8/jKNzFyH8MqD6wLv9tx+u9H6uvCv2LqWtHTLZh7XK5YgpusRRGf95+5RJrJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7ce06b89-9091-4820-b44a-fb0d61df4910",
                            TwoFactorEnabled = false,
                            UserName = "melissa@gmail.com"
                        });
                });

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserChatStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationUserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("ApplicationUserChats");
                });

            modelBuilder.Entity("Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatFrequencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatFrequencyId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ChatFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HulpverlenerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OuderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HulpverlenerId");

                    b.HasIndex("OuderId");

                    b.ToTable("ChatFrequencies");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AboveSixteen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("HulpverlenerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("HulpverlenerId");

                    b.ToTable("Clienten");
                });

            modelBuilder.Entity("Hulpverlener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("Behandeling")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverJou")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialisatie")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Study")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VestigingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VestigingId");

                    b.ToTable("Hulpverleners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "",
                            Behandeling = "Eerst moet er vastgesteld worden of je een eetstoornis hebt, en zo ja wat voor eetstoornis je hebt. Daarna kijken we hoe we jou kunnen helpen. Een eetstoornis is namelijk een psychische aandoening die niet vanzelf over gaat. We kunnen de eetstoornis het best behandelen met Cognitieve gedragstherapie. Cognitieve gedragstherapie is de meest onderzochte en effectieve psychologische behandeling bij eetstoornissen. In de behandeling wordt onder andere onderzocht welke gedachten er zijn over eten, gewicht en lichaamsvormen. Daarnaast wordt er ook onderzocht of deze gedachten kloppen. ",
                            Foto = "Screenshot_57.png",
                            Intro = "Ik heet Kees Closed, geboren in 1978 in Monster en de jongste van twee kinderen. Mijn ouders zijn gescheiden toen ik zes was en ik ben opgegroeid in het Westland. Ik ben heel nieuwsgierig naar het afwijkend eetgedrag van jongeren, waarom ze doen wat ze doen en wat hun verhaal is. Ik heb vroeger zelf last gehad van een eetstoornis en ben hier door middel van de juiste hulp vanaf gekomen. Dit heeft mij nieuwsgierig gemaakt naar hoe anderen dat ervaren en hoe ik hun daarmee kan helpen. ",
                            Name = "Kees",
                            OverJou = "Heb jij en vermoede dat je een eetstoornis hebt? Het grootste deel van de mensen heeft een verstoord lichaamsbeeld. Dit zorgt ervoor dat je bang bent om in gewicht aan te komen. Deze mensen letten vaak op wat ze eten, sporten overmatig of braken zelfs. Het gewicht wordt dan een obsessie en het lijnen, sporten of braken wordt een verslaving. ",
                            Specialisatie = "Eetstoornissen",
                            Study = "Ik heb orthopedagogiek gestudeerd aan de Universiteit van Leiden. Bij mijn afstuderen heb ik mij gespecialiseerd in de behandeling van eetstoornissen.  ",
                            VestigingId = 1
                        },
                        new
                        {
                            Id = 2,
                            Adres = "",
                            Behandeling = "Eerst gaan wij is een goed gesprek hebben over wie jij bent en wat je doet, ik ben namelijk heel benieuwd naar je. Daarna zal ik wat tests samen met jou afnemen. Deze test bestaan vooral Uit lees- en schrijfoefeningen. Waaruit we zullen zien of je wel daadwerkelijk dyslectie hebt. Zo ja, dan zullen we meer afspraken maken. Tijdens deze afspraken ga ik jou helpen met lezen en schrijven. We gaan samen werken aan trucjes die bij jou aansluiten om je zo goed mogelijk te helpen om op het juiste niveau te komen. ",
                            Foto = "Screenshot_58.png",
                            Intro = "Mijn naam is Krystel Vegter, geboren in 1990 in Honselersdijk en ik heb een broer. Mijn ouders zijn gescheiden toen ik zes was en ik ben opgegroeid in het Westland bij mijn moeder. Mijn hobby’s zijn schilderen, koken en een goed boek lezen. Door het scheiden van mijn ouders ben ik al op jongen leeftijd geïnteresseerd geraakt in beweegredenen van mensen en specifiek in jonge mensen die nog volop in ontwikkeling zijn. Door mijn nieuwsgierigheid te combineren met mijn interesse heb ik mijn perfecte beroep gevonden. ",
                            Name = "Krystel",
                            OverJou = "Er bestaat een vermoeden dat jij dyslectie hebt. Het is je opgevallen dat lezen toch langzamer gaat dan de rest van de kinderen/jongeren om je heen. Daarnaast zijn alle taalvakken moeilijk te volgen.   Waardoor ook schrijven je niet altijd even makkelijk afgaat. Grote kans dat een van je leraren dit is opgevallen en dit heeft aangegeven bij ons. Wees maar gerust want er is nog niks zeker en al zou je het wel hebben. dyslectie hoeft je schoolcarrière zeker niet in de weg te gaan zitten, want er zijn genoeg hulpmiddelen. ",
                            Specialisatie = "Dyslectie",
                            Study = "Ik heb gestudeerd aan de universiteit van leiden, waar ik mijn bachelor in psychologie heb gehaald en een master gespecialiseerd rondom problemen bij jongeren. ",
                            VestigingId = 1
                        },
                        new
                        {
                            Id = 3,
                            Adres = "",
                            Behandeling = "Wat we eerst doen is nagaan wat voor soort angststoornis jij te maken mee heeft. Dit doen we met een aantal testen. Jouw ouders of verzorgers mogen bij de testen zijn. Als het duidelijk is wat voor soort angststoornis het is gaan wij een behandelplan hiervoor samenstellen.   Eén van de eerste stappen is een gesprek voeren over gebeurtenissen in jouw leven. Dat is puur om uit te vogelen wat de angststoornis heeft veroorzaakt. Als we een oorzaak hebben gevonden kunnen progressieve gesprekken houden zodat jij in jouw vel zit. Je kan mij bellen of mailen voor meer informatie of vragen. We plannen gesprekken in om te zien hoe wij verder gaan erna. Ik help jouw heel graag en je bent van alle harte welkom. ",
                            Foto = "Screenshot_59.png",
                            Intro = "Mijn naam is Sugodies Allen, geboren in 1978 en opgegroeid in Den Haag, Ik ben de jongste in een gezin van zes kinderen. Mijn hobby’s zijn: lezen, schrijven en mensen helpen waar ik geschikt voor ben. Van jongs af aan wilde ik altijd iets doen om mensen met hun angst te helpen en overkomen. Hierdoor streef ik om een orthopedagoog te worden gespecialiseerd in cliënten helpen die te maken hebben met een angststoornis. ",
                            Name = "Sugodies Allen",
                            OverJou = "Angststoornis is dat je bang bent zelfs als de situatie geen gevaar geeft. Je raakt hierdoor in paniek en ook krijgen van serieuze klachten. Kenmerken van angststoornis die vaak gebeuren zijn: hoofdpijn, buikpijn, slaapproblemen en prikkelbaarheid. Maar ook bijzondere kenmerken: ademnood, hartkloppingen, tinteling of een doof gevoel in jouw ledematen. Er zijn nog vele andere kenmerken die je nog tegenaan loopt bij angststoornis. ",
                            Specialisatie = "Angststoornis",
                            Study = "Nadat ik klaar was met het VWO heb ik orthopedagogiek gestudeerd aan de Universiteit van Amsterdam. Bij het afstuderen heb ik mij gespecialiseerd in de behandelingen van angststoornissen. ",
                            VestigingId = 1
                        },
                        new
                        {
                            Id = 4,
                            Adres = "",
                            Behandeling = "We gaan gezamenlijk uitzoeken of jij ADHD hebt. Dit doen we door middel van een paar testen. Je ouder(s)/verzorger(s) mogen hier ook bij zijn als jij dat prettig vindt. De testen doen we omdat ik namelijk erg benieuwd ben naar jou en hoe jij ADHD ervaart. Op basis van deze testen kan ik oefeningen met je doen en tips geven om uiteindelijk beter met ADHD om te gaan.   Je bent zeer welkom en ik wil je graag helpen, als je nog meer informatie wilt kan je me gerust emaillen of bellen. ",
                            Foto = "Screenshot_60.png",
                            Intro = "Mijn naam is Melissa Wiedegem, geboren in 1995 in Rotterdam met een tweelingzus. Ik merkte op jonge leeftijd al dat ik een passie begon op te bouwen voor het helpen van anderen. Dit groeide later uit tot het helpen van kinderen met ADHD. ",
                            Name = "Melissa Wiedegem",
                            OverJou = "Bij jou bestaat het vermoeden dat je ADHD hebt. Als je dit hebt, werken je hersenen net iets anders dan bij iemand zonder ADHD. De meeste mensen hebben een soort filter in hun hersenen. Die zorgt ervoor dat niet alle prikkels (zoals geluiden of dingen in de omgeving) even hard binnen komen. Dit is bij ADHD anders. Bij ADHD komen er juist te veel prikkels binnen doordat er minder goed wordt gefilterd. Daardoor heb jij misschien moeite met het focussen op de belangrijke dingen van dat moment zonder afgeleid te worden. Zo zijn er nog meer dingen waar jij tegen aan kan lopen die bij ADHD horen. ",
                            Specialisatie = "ADHD",
                            Study = "Ik heb eerder al verschillende rollen vervuld zoals leerkracht en speciale leerkracht. In 2017 ben ik afgestudeerd als orthopedagoog aan de Universiteit van Utrecht. Ik heb mij bij het afstuderen gespecialiseerd in de behandeling van ADHD. ",
                            VestigingId = 1
                        });
                });

            modelBuilder.Entity("Melding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("HulpverlenerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HulpverlenerId");

                    b.ToTable("Meldingen");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "e8431a45-405f-4932-8819-46b179f1d3d3",
                            ConcurrencyStamp = "d80f1feb-9b07-4dd1-9d4c-b6420efe0d8e",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "ad376a8f-9eab-4bb9-9fca-30b01540f445",
                            ConcurrencyStamp = "3221c4c5-7527-4303-92c4-d880c48f3a93",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "21879a36-cc2c-4fb9-9213-2708b962b92e",
                            ConcurrencyStamp = "37f1c107-b808-413c-bfa0-46bfd0aaf882",
                            Name = "Hulpverlener",
                            NormalizedName = "HULPVERLENER"
                        },
                        new
                        {
                            Id = "3e0f2af8-69ce-4d39-ae6a-440e388b3ca3",
                            ConcurrencyStamp = "d2055fd5-dd65-41fc-93ae-8f2a5d9a340d",
                            Name = "Ouder",
                            NormalizedName = "OUDER"
                        },
                        new
                        {
                            Id = "e7c5f138-26ff-4413-a2e2-273a11c334d4",
                            ConcurrencyStamp = "75c1e5f4-5c51-4bd3-9cb2-d844a218f2ef",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e574",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        },
                        new
                        {
                            UserId = "6c26c683-3d56-4b10-a671-9c0565acba97",
                            RoleId = "21879a36-cc2c-4fb9-9213-2708b962b92e"
                        },
                        new
                        {
                            UserId = "4a02ed90-00c0-4a74-b95e-a54722f1c734",
                            RoleId = "21879a36-cc2c-4fb9-9213-2708b962b92e"
                        },
                        new
                        {
                            UserId = "8c74234a-facb-40fb-b812-f45b1f328867",
                            RoleId = "21879a36-cc2c-4fb9-9213-2708b962b92e"
                        },
                        new
                        {
                            UserId = "e0fd4978-7f42-42d9-a3d8-0efbdd40188b",
                            RoleId = "21879a36-cc2c-4fb9-9213-2708b962b92e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Moderator");
                });

            modelBuilder.Entity("Ouder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Ouders");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isHandled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("MessageId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SelfHelpGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AboveSixteen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("SelfHelpGroups");
                });

            modelBuilder.Entity("Vestiging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vestigingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Melis Stokelaan 156",
                            Name = "Vesteging Den Haag",
                            Plaats = "Den Haag"
                        });
                });

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.HasOne("Client", "Client")
                        .WithOne("Aanmelding")
                        .HasForeignKey("Aanmelding", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hulpverlener", "Hulpverlener")
                        .WithMany()
                        .HasForeignKey("HulpverlenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ouder", "Ouder")
                        .WithOne("Aanmelding")
                        .HasForeignKey("Aanmelding", "OuderId");

                    b.Navigation("Client");

                    b.Navigation("Hulpverlener");

                    b.Navigation("Ouder");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.HasOne("Client", "Client")
                        .WithOne("Account")
                        .HasForeignKey("ApplicationUser", "ClientId");

                    b.HasOne("Hulpverlener", "Hulpverlener")
                        .WithOne("Account")
                        .HasForeignKey("ApplicationUser", "HulpverlenerId");

                    b.HasOne("Ouder", "Ouder")
                        .WithOne("Account")
                        .HasForeignKey("ApplicationUser", "OuderId");

                    b.Navigation("Client");

                    b.Navigation("Hulpverlener");

                    b.Navigation("Ouder");
                });

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.HasOne("ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserChats")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat", "Chat")
                        .WithMany("ApplicationUserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Chat", b =>
                {
                    b.HasOne("ChatFrequency", "ChatFrequency")
                        .WithOne("Chat")
                        .HasForeignKey("Chat", "ChatFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChatFrequency");
                });

            modelBuilder.Entity("ChatFrequency", b =>
                {
                    b.HasOne("Hulpverlener", "Hulpverlener")
                        .WithMany("ChatFrequencies")
                        .HasForeignKey("HulpverlenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ouder", "Ouder")
                        .WithMany("ChatFrequencies")
                        .HasForeignKey("OuderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hulpverlener");

                    b.Navigation("Ouder");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.HasOne("Hulpverlener", "Hulpverlener")
                        .WithMany("Clients")
                        .HasForeignKey("HulpverlenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hulpverlener");
                });

            modelBuilder.Entity("Hulpverlener", b =>
                {
                    b.HasOne("Vestiging", null)
                        .WithMany("Hulpverleners")
                        .HasForeignKey("VestigingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Melding", b =>
                {
                    b.HasOne("Hulpverlener", "Hulpverlener")
                        .WithMany("Meldingen")
                        .HasForeignKey("HulpverlenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hulpverlener");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moderator", b =>
                {
                    b.HasOne("ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Ouder", b =>
                {
                    b.HasOne("Client", "Client")
                        .WithOne("Ouder")
                        .HasForeignKey("Ouder", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.HasOne("ApplicationUser", "Handler")
                        .WithMany("HandledReports")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Message", "Message")
                        .WithMany("Reports")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handler");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SelfHelpGroup", b =>
                {
                    b.HasOne("Chat", "Chat")
                        .WithOne("SelfHelpGroup")
                        .HasForeignKey("SelfHelpGroup", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserChats");

                    b.Navigation("HandledReports");
                });

            modelBuilder.Entity("Chat", b =>
                {
                    b.Navigation("ApplicationUserChats");

                    b.Navigation("SelfHelpGroup");
                });

            modelBuilder.Entity("ChatFrequency", b =>
                {
                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Navigation("Aanmelding");

                    b.Navigation("Account");

                    b.Navigation("Ouder");
                });

            modelBuilder.Entity("Hulpverlener", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ChatFrequencies");

                    b.Navigation("Clients");

                    b.Navigation("Meldingen");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Ouder", b =>
                {
                    b.Navigation("Aanmelding");

                    b.Navigation("Account");

                    b.Navigation("ChatFrequencies");
                });

            modelBuilder.Entity("Vestiging", b =>
                {
                    b.Navigation("Hulpverleners");
                });
#pragma warning restore 612, 618
        }
    }
}
